# Generated by Django 5.2.8 on 2026-01-24 23:55

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'taxonomies',
                'db_table': 'taxonomy',
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user_account',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('attributes', models.JSONField(blank=True, null=True)),
                ('external_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'candidate',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_group',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('scope', models.CharField(choices=[('global', 'Global'), ('candidate_type', 'Candidate Type'), ('session', 'Session'), ('group', 'Group')], max_length=50)),
                ('candidate_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'question',
                'indexes': [models.Index(fields=['scope'], name='question_scope_284889_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('order_num', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='core.question')),
            ],
            options={
                'db_table': 'answer_option',
                'ordering': ['order_num'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('candidate_type', models.CharField(blank=True, max_length=100, null=True)),
                ('rules', models.JSONField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('archived', 'Archived')], default='open', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.group')),
            ],
            options={
                'db_table': 'session',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.JSONField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.candidate')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.session')),
            ],
            options={
                'db_table': 'match',
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='core.session'),
        ),
        migrations.CreateModel(
            name='SessionSharedGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_sessions', to='core.group')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_groups', to='core.session')),
            ],
            options={
                'db_table': 'session_shared_group',
            },
        ),
        migrations.CreateModel(
            name='Swipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_like', models.BooleanField()),
                ('swiped_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to='core.candidate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'swipe',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('attributes', models.JSONField(blank=True, null=True)),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='core.taxonomy')),
            ],
            options={
                'db_table': 'term',
            },
        ),
        migrations.CreateModel(
            name='CandidateTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_terms', to='core.candidate')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_terms', to='core.term')),
            ],
            options={
                'db_table': 'candidate_term',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_value', models.JSONField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('answer_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_answers', to='core.answeroption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='core.question')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='core.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_answer',
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=50)),
                ('membership_type', models.CharField(choices=[('invitation', 'Invitation'), ('request', 'Request')], default='invitation', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_membership',
                'indexes': [models.Index(fields=['group', 'is_confirmed'], name='group_membe_group_i_af8718_idx'), models.Index(fields=['group', 'status'], name='group_membe_group_i_990501_idx'), models.Index(fields=['user', 'status'], name='group_membe_user_id_ce33d8_idx'), models.Index(fields=['membership_type', 'status'], name='group_membe_members_0218b2_idx')],
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MatchMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'match_message',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['match'], name='match_messa_match_i_0bc6ea_idx'), models.Index(fields=['user'], name='match_messa_user_id_46b57a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='answeroption',
            index=models.Index(fields=['question'], name='answer_opti_questio_998384_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['group'], name='session_group_i_fb2768_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['status'], name='session_status_dd82f4_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['session'], name='match_session_e6f74f_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['candidate'], name='match_candida_547b65_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('session', 'candidate')},
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['session'], name='candidate_session_051d8b_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['created_by'], name='candidate_created_3d8665_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('session', 'external_ref', 'label')},
        ),
        migrations.AddIndex(
            model_name='sessionsharedgroup',
            index=models.Index(fields=['session'], name='session_sha_session_f0e989_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionsharedgroup',
            index=models.Index(fields=['group'], name='session_sha_group_i_35c093_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionsharedgroup',
            unique_together={('session', 'group')},
        ),
        migrations.AddIndex(
            model_name='swipe',
            index=models.Index(fields=['candidate'], name='swipe_candida_201e00_idx'),
        ),
        migrations.AddIndex(
            model_name='swipe',
            index=models.Index(fields=['user'], name='swipe_user_id_5fa453_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='swipe',
            unique_together={('user', 'candidate')},
        ),
        migrations.AddIndex(
            model_name='term',
            index=models.Index(fields=['taxonomy'], name='term_taxonom_b44977_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('taxonomy', 'value')},
        ),
        migrations.AddIndex(
            model_name='candidateterm',
            index=models.Index(fields=['candidate'], name='candidate_t_candida_a5b9df_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateterm',
            index=models.Index(fields=['term'], name='candidate_t_term_id_1f29d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidateterm',
            unique_together={('candidate', 'term')},
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['user'], name='user_answer_user_id_bf874f_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['question'], name='user_answer_questio_47cb98_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['session'], name='user_answer_session_3faaeb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('user', 'question', 'session')},
        ),
    ]
