# Generated by Django 5.2.10 on 2026-01-29 21:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_country_and_region_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='HobbyTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'hobby_tag',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=50)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('cover_url', models.URLField(blank=True, max_length=500, null=True)),
                ('current_location', models.CharField(blank=True, max_length=100)),
                ('home_base', models.CharField(blank=True, max_length=100)),
                ('has_van', models.BooleanField(default=False)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('followers_only', 'Followers Only'), ('private', 'Private')], default='public', max_length=20)),
                ('interested_in_dating', models.BooleanField(default=False)),
                ('interested_in_friends', models.BooleanField(default=True)),
                ('travel_status', models.CharField(blank=True, choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('weekender', 'Weekender'), ('aspiring', 'Aspiring')], max_length=20, null=True)),
                ('travel_companions', models.CharField(blank=True, choices=[('solo', 'Solo'), ('couple', 'Couple'), ('family', 'Family'), ('with_pets', 'With Pets')], max_length=20, null=True)),
                ('work_status', models.CharField(blank=True, choices=[('remote_worker', 'Remote Worker'), ('retired', 'Retired'), ('seasonal_worker', 'Seasonal Worker'), ('unemployed', 'Unemployed'), ('other', 'Other')], max_length=20, null=True)),
                ('camping_preferences', models.JSONField(blank=True, default=list)),
                ('travel_pace', models.CharField(blank=True, choices=[('slow', 'Slow Travel'), ('moderate', 'Moderate'), ('fast', 'Fast Mover')], max_length=20, null=True)),
                ('now_in_updated_at', models.DateTimeField(blank=True, null=True)),
                ('next_week_in_updated_at', models.DateTimeField(blank=True, null=True)),
                ('next_month_in_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('next_month_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles_next_month', to='core.region')),
                ('next_week_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles_next_week', to='core.region')),
                ('now_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles_now', to='core.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='ProfileHobby',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hobby_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_hobbies', to='core.hobbytag')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_hobbies', to='core.profile')),
            ],
            options={
                'db_table': 'profile_hobby',
                'unique_together': {('profile', 'hobby_tag')},
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='hobbies',
            field=models.ManyToManyField(related_name='profiles', through='core.ProfileHobby', to='core.hobbytag'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['now_in'], name='profile_now_in__ad2c8e_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['next_week_in'], name='profile_next_we_793543_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['next_month_in'], name='profile_next_mo_a09eeb_idx'),
        ),
    ]
