# Generated by Django 5.2.10 on 2026-01-29 21:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_profile_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(choices=[('van', 'Van'), ('rv', 'RV'), ('truck_camper', 'Truck Camper'), ('skoolie', 'Skoolie'), ('trailer', 'Trailer'), ('car_camper', 'Car Camper'), ('other', 'Other')], max_length=20)),
                ('make', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('build_status', models.CharField(blank=True, choices=[('stock', 'Stock'), ('partial', 'Partial Build'), ('full', 'Full Build')], max_length=20, null=True)),
                ('nickname', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='core.profile')),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
        migrations.CreateModel(
            name='VehiclePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField(max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.vehicle')),
            ],
            options={
                'db_table': 'vehicle_photo',
                'ordering': ['display_order'],
                'indexes': [models.Index(fields=['vehicle'], name='vehicle_pho_vehicle_673826_idx')],
            },
        ),
    ]
