# Generated by Django 5.2.10 on 2026-01-29 21:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_vehicle_and_vehiclephoto_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to='core.profile')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_set', to='core.profile')),
            ],
            options={
                'db_table': 'follow',
                'indexes': [models.Index(fields=['follower'], name='follow_followe_1b4118_idx'), models.Index(fields=['following'], name='follow_followi_88b73a_idx')],
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
