# Generated by Django 5.2.10 on 2026-01-29 23:38

from django.db import migrations


def seed_location_data(apps, schema_editor):
    """
    Seed the database with countries and regions for van lifer location selection.
    Uses get_or_create to be idempotent (safe to run multiple times).
    """
    Country = apps.get_model('core', 'Country')
    Region = apps.get_model('core', 'Region')
    
    # Define countries and their regions
    location_data = {
        # United States
        ('United States', 'US'): [
            'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
            'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia',
            'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa',
            'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
            'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri',
            'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey',
            'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio',
            'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina',
            'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont',
            'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming',
            'District of Columbia',
        ],
        # Canada
        ('Canada', 'CA'): [
            'Alberta', 'British Columbia', 'Manitoba', 'New Brunswick',
            'Newfoundland and Labrador', 'Northwest Territories', 'Nova Scotia',
            'Nunavut', 'Ontario', 'Prince Edward Island', 'Quebec',
            'Saskatchewan', 'Yukon',
        ],
        # Mexico
        ('Mexico', 'MX'): [
            'Aguascalientes', 'Baja California', 'Baja California Sur', 'Campeche',
            'Chiapas', 'Chihuahua', 'Coahuila', 'Colima', 'Durango',
            'Guanajuato', 'Guerrero', 'Hidalgo', 'Jalisco', 'Mexico City',
            'Mexico State', 'Michoacan', 'Morelos', 'Nayarit', 'Nuevo Leon',
            'Oaxaca', 'Puebla', 'Queretaro', 'Quintana Roo', 'San Luis Potosi',
            'Sinaloa', 'Sonora', 'Tabasco', 'Tamaulipas', 'Tlaxcala',
            'Veracruz', 'Yucatan', 'Zacatecas',
        ],
        # Australia
        ('Australia', 'AU'): [
            'Australian Capital Territory', 'New South Wales', 'Northern Territory',
            'Queensland', 'South Australia', 'Tasmania', 'Victoria', 'Western Australia',
        ],
        # New Zealand
        ('New Zealand', 'NZ'): [
            'Auckland', 'Bay of Plenty', 'Canterbury', 'Gisborne', 'Hawkes Bay',
            'Manawatu-Whanganui', 'Marlborough', 'Nelson', 'Northland', 'Otago',
            'Southland', 'Taranaki', 'Tasman', 'Waikato', 'Wellington',
            'West Coast',
        ],
        # United Kingdom
        ('United Kingdom', 'GB'): [
            'England', 'Scotland', 'Wales', 'Northern Ireland',
        ],
        # Germany
        ('Germany', 'DE'): [
            'Baden-Wurttemberg', 'Bavaria', 'Berlin', 'Brandenburg', 'Bremen',
            'Hamburg', 'Hesse', 'Lower Saxony', 'Mecklenburg-Vorpommern',
            'North Rhine-Westphalia', 'Rhineland-Palatinate', 'Saarland',
            'Saxony', 'Saxony-Anhalt', 'Schleswig-Holstein', 'Thuringia',
        ],
        # France
        ('France', 'FR'): [
            'Auvergne-Rhone-Alpes', 'Bourgogne-Franche-Comte', 'Brittany',
            'Centre-Val de Loire', 'Corsica', 'Grand Est', 'Hauts-de-France',
            'Ile-de-France', 'Normandy', 'Nouvelle-Aquitaine', 'Occitanie',
            'Pays de la Loire', 'Provence-Alpes-Cote d\'Azur',
        ],
        # Spain
        ('Spain', 'ES'): [
            'Andalusia', 'Aragon', 'Asturias', 'Balearic Islands', 'Basque Country',
            'Canary Islands', 'Cantabria', 'Castile and Leon', 'Castile-La Mancha',
            'Catalonia', 'Extremadura', 'Galicia', 'La Rioja', 'Madrid',
            'Murcia', 'Navarre', 'Valencia',
        ],
        # Portugal
        ('Portugal', 'PT'): [
            'Alentejo', 'Algarve', 'Azores', 'Centro', 'Lisbon', 'Madeira', 'Norte',
        ],
        # Italy
        ('Italy', 'IT'): [
            'Abruzzo', 'Aosta Valley', 'Apulia', 'Basilicata', 'Calabria',
            'Campania', 'Emilia-Romagna', 'Friuli Venezia Giulia', 'Lazio',
            'Liguria', 'Lombardy', 'Marche', 'Molise', 'Piedmont',
            'Sardinia', 'Sicily', 'Trentino-Alto Adige', 'Tuscany',
            'Umbria', 'Veneto',
        ],
        # Netherlands
        ('Netherlands', 'NL'): [
            'Drenthe', 'Flevoland', 'Friesland', 'Gelderland', 'Groningen',
            'Limburg', 'North Brabant', 'North Holland', 'Overijssel',
            'South Holland', 'Utrecht', 'Zeeland',
        ],
        # Belgium
        ('Belgium', 'BE'): [
            'Brussels', 'Flanders', 'Wallonia',
        ],
        # Switzerland
        ('Switzerland', 'CH'): [
            'Aargau', 'Appenzell Ausserrhoden', 'Appenzell Innerrhoden',
            'Basel-Landschaft', 'Basel-Stadt', 'Bern', 'Fribourg', 'Geneva',
            'Glarus', 'Graubunden', 'Jura', 'Lucerne', 'Neuchatel',
            'Nidwalden', 'Obwalden', 'Schaffhausen', 'Schwyz', 'Solothurn',
            'St. Gallen', 'Thurgau', 'Ticino', 'Uri', 'Valais', 'Vaud',
            'Zug', 'Zurich',
        ],
        # Austria
        ('Austria', 'AT'): [
            'Burgenland', 'Carinthia', 'Lower Austria', 'Salzburg', 'Styria',
            'Tyrol', 'Upper Austria', 'Vienna', 'Vorarlberg',
        ],
        # Norway
        ('Norway', 'NO'): [
            'Agder', 'Innlandet', 'More og Romsdal', 'Nordland', 'Oslo',
            'Rogaland', 'Troms og Finnmark', 'Trondelag', 'Vestfold og Telemark',
            'Vestland', 'Viken',
        ],
        # Sweden
        ('Sweden', 'SE'): [
            'Blekinge', 'Dalarna', 'Gavleborg', 'Gotland', 'Halland',
            'Jamtland', 'Jonkoping', 'Kalmar', 'Kronoberg', 'Norrbotten',
            'Orebro', 'Ostergotland', 'Skane', 'Sodermanland', 'Stockholm',
            'Uppsala', 'Varmland', 'Vasterbotten', 'Vasternorrland',
            'Vastmanland', 'Vastra Gotaland',
        ],
        # Iceland
        ('Iceland', 'IS'): [
            'Capital Region', 'Eastern Region', 'Northeastern Region',
            'Northwestern Region', 'Southern Peninsula', 'Southern Region',
            'Western Region', 'Westfjords',
        ],
        # Ireland
        ('Ireland', 'IE'): [
            'Connacht', 'Leinster', 'Munster', 'Ulster',
        ],
        # Costa Rica
        ('Costa Rica', 'CR'): [
            'Alajuela', 'Cartago', 'Guanacaste', 'Heredia', 'Limon',
            'Puntarenas', 'San Jose',
        ],
        # Panama
        ('Panama', 'PA'): [
            'Bocas del Toro', 'Chiriqui', 'Cocle', 'Colon', 'Darien',
            'Herrera', 'Los Santos', 'Panama', 'Panama Oeste', 'Veraguas',
        ],
        # Guatemala
        ('Guatemala', 'GT'): [
            'Alta Verapaz', 'Baja Verapaz', 'Chimaltenango', 'Chiquimula',
            'El Progreso', 'Escuintla', 'Guatemala', 'Huehuetenango', 'Izabal',
            'Jalapa', 'Jutiapa', 'Peten', 'Quetzaltenango', 'Quiche',
            'Retalhuleu', 'Sacatepequez', 'San Marcos', 'Santa Rosa',
            'Solola', 'Suchitepequez', 'Totonicapan', 'Zacapa',
        ],
        # Belize
        ('Belize', 'BZ'): [
            'Belize', 'Cayo', 'Corozal', 'Orange Walk', 'Stann Creek', 'Toledo',
        ],
        # Argentina
        ('Argentina', 'AR'): [
            'Buenos Aires', 'Catamarca', 'Chaco', 'Chubut', 'Cordoba',
            'Corrientes', 'Entre Rios', 'Formosa', 'Jujuy', 'La Pampa',
            'La Rioja', 'Mendoza', 'Misiones', 'Neuquen', 'Rio Negro',
            'Salta', 'San Juan', 'San Luis', 'Santa Cruz', 'Santa Fe',
            'Santiago del Estero', 'Tierra del Fuego', 'Tucuman',
        ],
        # Chile
        ('Chile', 'CL'): [
            'Antofagasta', 'Araucania', 'Arica y Parinacota', 'Atacama',
            'Aysen', 'Biobio', 'Coquimbo', 'Los Lagos', 'Los Rios',
            'Magallanes', 'Maule', 'Nuble', 'O\'Higgins', 'Santiago Metropolitan',
            'Tarapaca', 'Valparaiso',
        ],
        # Brazil
        ('Brazil', 'BR'): [
            'Acre', 'Alagoas', 'Amapa', 'Amazonas', 'Bahia', 'Ceara',
            'Distrito Federal', 'Espirito Santo', 'Goias', 'Maranhao',
            'Mato Grosso', 'Mato Grosso do Sul', 'Minas Gerais', 'Para',
            'Paraiba', 'Parana', 'Pernambuco', 'Piaui', 'Rio de Janeiro',
            'Rio Grande do Norte', 'Rio Grande do Sul', 'Rondonia', 'Roraima',
            'Santa Catarina', 'Sao Paulo', 'Sergipe', 'Tocantins',
        ],
        # Colombia
        ('Colombia', 'CO'): [
            'Amazonas', 'Antioquia', 'Arauca', 'Atlantico', 'Bogota',
            'Bolivar', 'Boyaca', 'Caldas', 'Caqueta', 'Casanare', 'Cauca',
            'Cesar', 'Choco', 'Cordoba', 'Cundinamarca', 'Guainia',
            'Guaviare', 'Huila', 'La Guajira', 'Magdalena', 'Meta',
            'Narino', 'Norte de Santander', 'Putumayo', 'Quindio',
            'Risaralda', 'San Andres y Providencia', 'Santander', 'Sucre',
            'Tolima', 'Valle del Cauca', 'Vaupes', 'Vichada',
        ],
        # Peru
        ('Peru', 'PE'): [
            'Amazonas', 'Ancash', 'Apurimac', 'Arequipa', 'Ayacucho',
            'Cajamarca', 'Callao', 'Cusco', 'Huancavelica', 'Huanuco',
            'Ica', 'Junin', 'La Libertad', 'Lambayeque', 'Lima', 'Loreto',
            'Madre de Dios', 'Moquegua', 'Pasco', 'Piura', 'Puno',
            'San Martin', 'Tacna', 'Tumbes', 'Ucayali',
        ],
        # Ecuador
        ('Ecuador', 'EC'): [
            'Azuay', 'Bolivar', 'Canar', 'Carchi', 'Chimborazo', 'Cotopaxi',
            'El Oro', 'Esmeraldas', 'Galapagos', 'Guayas', 'Imbabura',
            'Loja', 'Los Rios', 'Manabi', 'Morona Santiago', 'Napo',
            'Orellana', 'Pastaza', 'Pichincha', 'Santa Elena',
            'Santo Domingo de los Tsachilas', 'Sucumbios', 'Tungurahua',
            'Zamora Chinchipe',
        ],
        # Japan
        ('Japan', 'JP'): [
            'Hokkaido', 'Tohoku', 'Kanto', 'Chubu', 'Kansai', 'Chugoku',
            'Shikoku', 'Kyushu', 'Okinawa',
        ],
        # South Africa
        ('South Africa', 'ZA'): [
            'Eastern Cape', 'Free State', 'Gauteng', 'KwaZulu-Natal', 'Limpopo',
            'Mpumalanga', 'North West', 'Northern Cape', 'Western Cape',
        ],
        # Morocco
        ('Morocco', 'MA'): [
            'Beni Mellal-Khenifra', 'Casablanca-Settat', 'Draa-Tafilalet',
            'Fes-Meknes', 'Guelmim-Oued Noun', 'Laayoune-Sakia El Hamra',
            'Marrakech-Safi', 'Oriental', 'Rabat-Sale-Kenitra',
            'Souss-Massa', 'Tanger-Tetouan-Al Hoceima',
        ],
        # Greece
        ('Greece', 'GR'): [
            'Attica', 'Central Greece', 'Central Macedonia', 'Crete',
            'Eastern Macedonia and Thrace', 'Epirus', 'Ionian Islands',
            'North Aegean', 'Peloponnese', 'South Aegean', 'Thessaly',
            'Western Greece', 'Western Macedonia',
        ],
        # Croatia
        ('Croatia', 'HR'): [
            'Bjelovar-Bilogora', 'Brod-Posavina', 'Dubrovnik-Neretva',
            'Istria', 'Karlovac', 'Koprivnica-Krizevci', 'Krapina-Zagorje',
            'Lika-Senj', 'Medimurje', 'Osijek-Baranja', 'Pozega-Slavonia',
            'Primorje-Gorski Kotar', 'Sibenik-Knin', 'Sisak-Moslavina',
            'Split-Dalmatia', 'Varazdin', 'Virovitica-Podravina',
            'Vukovar-Srijem', 'Zadar', 'Zagreb', 'Zagreb County',
        ],
        # Slovenia
        ('Slovenia', 'SI'): [
            'Central Slovenia', 'Coastal-Karst', 'Drava', 'Gorizia',
            'Inner Carniola-Karst', 'Lower Sava', 'Mura', 'Savinja',
            'Southeast Slovenia', 'Upper Carniola',
        ],
        # Montenegro
        ('Montenegro', 'ME'): [
            'Andrijevica', 'Bar', 'Berane', 'Bijelo Polje', 'Budva',
            'Cetinje', 'Danilovgrad', 'Herceg Novi', 'Kolasin', 'Kotor',
            'Mojkovac', 'Niksic', 'Plav', 'Pljevlja', 'Pluzine',
            'Podgorica', 'Rozaje', 'Savnik', 'Tivat', 'Ulcinj', 'Zabljak',
        ],
        # Albania
        ('Albania', 'AL'): [
            'Berat', 'Diber', 'Durres', 'Elbasan', 'Fier', 'Gjirokaster',
            'Korce', 'Kukes', 'Lezhe', 'Shkoder', 'Tirana', 'Vlore',
        ],
        # Thailand
        ('Thailand', 'TH'): [
            'Bangkok', 'Central Thailand', 'Eastern Thailand',
            'Northeastern Thailand', 'Northern Thailand', 'Southern Thailand',
            'Western Thailand',
        ],
        # Vietnam
        ('Vietnam', 'VN'): [
            'Central Highlands', 'Mekong Delta', 'North Central Coast',
            'Northeast', 'Northwest', 'Red River Delta',
            'South Central Coast', 'Southeast',
        ],
        # Indonesia
        ('Indonesia', 'ID'): [
            'Bali', 'Java', 'Kalimantan', 'Nusa Tenggara', 'Papua',
            'Sulawesi', 'Sumatra',
        ],
        # Philippines
        ('Philippines', 'PH'): [
            'Bicol', 'Cagayan Valley', 'Calabarzon', 'Caraga',
            'Central Luzon', 'Central Visayas', 'Cordillera', 'Davao',
            'Eastern Visayas', 'Ilocos', 'Metro Manila', 'Mimaropa',
            'Northern Mindanao', 'Soccsksargen', 'Western Visayas', 'Zamboanga',
        ],
    }
    
    # Create countries and regions
    for (country_name, country_code), regions in location_data.items():
        country, _ = Country.objects.get_or_create(
            code=country_code,
            defaults={'name': country_name}
        )
        
        for region_name in regions:
            Region.objects.get_or_create(
                country=country,
                name=region_name
            )


def reverse_seed_location_data(apps, schema_editor):
    """
    Reverse migration - remove seeded location data.
    Note: This will only remove data if no profiles reference these locations.
    """
    Country = apps.get_model('core', 'Country')
    Region = apps.get_model('core', 'Region')
    
    # Delete all regions first (due to foreign key constraint)
    Region.objects.all().delete()
    # Then delete all countries
    Country.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_create_follow_model'),
    ]

    operations = [
        migrations.RunPython(seed_location_data, reverse_seed_location_data),
    ]
