# Generated by Django 5.2.10 on 2026-01-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_seed_location_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='group_description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='looking_for_dating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='looking_for_friends',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='meetup_interest',
            field=models.CharField(choices=[('actively_looking', 'Actively Looking'), ('open_to_it', 'Open To It'), ('selective', 'Selective'), ('solo_mode', 'Solo Mode')], default='open_to_it', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('solo', 'Solo'), ('couple', 'Couple'), ('group', 'Group')], default='solo', max_length=20),
        ),
    ]
