# Generated by Django 5.2.10 on 2026-01-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_profile_type_and_intent_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_pets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='lifestyle_environment',
            field=models.CharField(blank=True, choices=[('outdoors', 'Outdoors'), ('city_mix', 'City Mix')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lifestyle_schedule',
            field=models.CharField(blank=True, choices=[('early_bird', 'Early Bird'), ('night_owl', 'Night Owl')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lifestyle_social',
            field=models.CharField(blank=True, choices=[('quiet', 'Quiet'), ('party', 'Party')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pet_friendly_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='pet_type',
            field=models.CharField(blank=True, choices=[('dog', 'Dog'), ('cat', 'Cat'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='rig_status',
            field=models.CharField(blank=True, choices=[('van', 'Van'), ('rv', 'RV'), ('truck_camper', 'Truck Camper'), ('skoolie', 'Skoolie'), ('car', 'Car'), ('no_vehicle', 'No Vehicle'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_vibe',
            field=models.CharField(blank=True, choices=[('introvert', 'Introvert'), ('balanced', 'Balanced'), ('social', 'Social')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='travel_pace',
            field=models.CharField(blank=True, choices=[('slow', 'Slow (weeks per spot)'), ('mixed', 'Mixed (varies)'), ('fast', 'Fast (moves frequently)')], max_length=20, null=True),
        ),
    ]
