# Generated by Django 5.2.10 on 2026-01-31 15:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_travel_lifestyle_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='InTownWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city_area', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_town_windows', to='core.profile')),
            ],
            options={
                'db_table': 'in_town_window',
                'ordering': ['start_date'],
                'indexes': [models.Index(fields=['profile'], name='in_town_win_profile_c445ff_idx'), models.Index(fields=['start_date', 'end_date'], name='in_town_win_start_d_90afa8_idx')],
            },
        ),
    ]
