# Generated by Django 5.2.10 on 2026-01-31 15:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_create_in_town_window'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_question', models.CharField(choices=[('perfect_day', 'My perfect day on the road looks like...'), ('cant_live_without', "I can't live without..."), ('looking_for', "I'm looking for someone who..."), ('best_adventure', 'My best adventure so far...'), ('next_destination', 'My next dream destination is...'), ('van_life_lesson', 'The biggest lesson van life taught me...'), ('ideal_travel_buddy', 'My ideal travel buddy is...'), ('hidden_talent', 'My hidden talent is...')], max_length=50)),
                ('prompt_answer', models.TextField(max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='core.profile')),
            ],
            options={
                'db_table': 'profile_prompt',
                'ordering': ['display_order'],
                'unique_together': {('profile', 'prompt_question')},
            },
        ),
    ]
