# Generated by Django 5.2.10 on 2026-01-31 16:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_create_profile_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('dating', 'Dating'), ('friends', 'Friends')], max_length=20)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user1', to='core.profile')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user2', to='core.profile')),
            ],
            options={
                'db_table': 'person_match',
                'indexes': [models.Index(fields=['user1', 'is_active'], name='person_matc_user1_i_50161d_idx'), models.Index(fields=['user2', 'is_active'], name='person_matc_user2_i_3535b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='PersonSwipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_like', models.BooleanField()),
                ('mode', models.CharField(choices=[('dating', 'Dating'), ('friends', 'Friends')], max_length=20)),
                ('swiped_at', models.DateTimeField(auto_now_add=True)),
                ('swiped_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes_received', to='core.profile')),
                ('swiper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes_made', to='core.profile')),
            ],
            options={
                'db_table': 'person_swipe',
                'indexes': [models.Index(fields=['swiper', 'mode'], name='person_swip_swiper__af1fe4_idx'), models.Index(fields=['swiped_on', 'mode'], name='person_swip_swiped__296801_idx'), models.Index(fields=['swiped_on', 'is_like', 'mode'], name='person_swip_swiped__d11c73_idx')],
                'unique_together': {('swiper', 'swiped_on', 'mode')},
            },
        ),
    ]
