# Generated by Django 5.2.10 on 2026-01-31 17:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_person_swipe_and_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=1000)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('mini_card', 'Mini Card'), ('icebreaker', 'Icebreaker')], default='text', max_length=20)),
                ('mini_card_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.personmatch')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_direct_messages', to='core.profile')),
            ],
            options={
                'db_table': 'direct_message',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['match', 'created_at'], name='direct_mess_match_i_297fe6_idx'), models.Index(fields=['sender'], name='direct_mess_sender__2f29e4_idx')],
            },
        ),
    ]
