# Generated by Django 5.2.10 on 2026-02-01 14:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_create_direct_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to='core.profile')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_made', to='core.profile')),
            ],
            options={
                'db_table': 'user_block',
                'indexes': [models.Index(fields=['blocker'], name='user_block_blocker_eb3888_idx'), models.Index(fields=['blocked'], name='user_block_blocked_331146_idx')],
                'unique_together': {('blocker', 'blocked')},
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('harassment', 'Harassment'), ('spam', 'Spam'), ('inappropriate_content', 'Inappropriate Content'), ('fake_profile', 'Fake Profile'), ('scam', 'Scam'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to='core.profile')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to='core.profile')),
            ],
            options={
                'db_table': 'user_report',
                'indexes': [models.Index(fields=['reporter'], name='user_report_reporte_1c76d1_idx'), models.Index(fields=['reported'], name='user_report_reporte_e8aaa5_idx'), models.Index(fields=['reason'], name='user_report_reason_c7d7c3_idx'), models.Index(fields=['created_at'], name='user_report_created_2f3dce_idx')],
            },
        ),
    ]
