# Generated by Django 5.2.10 on 2026-02-01 15:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_user_block_and_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('coffee', 'Coffee'), ('sunrise_hike', 'Sunrise Hike'), ('dog_walk', 'Dog Walk'), ('cowork', 'Cowork Session'), ('sunset', 'Sunset Viewpoint'), ('other', 'Other')], max_length=20)),
                ('plan_date', models.DateField()),
                ('time_window', models.CharField(choices=[('morning', 'Morning (6am-12pm)'), ('afternoon', 'Afternoon (12pm-5pm)'), ('evening', 'Evening (5pm-9pm)'), ('flexible', 'Flexible')], max_length=20)),
                ('meetup_area', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('max_attendees', models.PositiveIntegerField(default=6)),
                ('status', models.CharField(choices=[('open', 'Open'), ('full', 'Full'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_plans', to='core.profile')),
            ],
            options={
                'db_table': 'plan',
                'ordering': ['plan_date', 'time_window'],
            },
        ),
        migrations.CreateModel(
            name='PlanAttendee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('joined', 'Joined'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='joined', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='core.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_attendances', to='core.profile')),
            ],
            options={
                'db_table': 'plan_attendee',
            },
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['created_by'], name='plan_created_d45e71_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['plan_date', 'status'], name='plan_plan_da_6cdd23_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['meetup_area'], name='plan_meetup__76a1f8_idx'),
        ),
        migrations.AddIndex(
            model_name='planattendee',
            index=models.Index(fields=['plan', 'status'], name='plan_attend_plan_id_4597b5_idx'),
        ),
        migrations.AddIndex(
            model_name='planattendee',
            index=models.Index(fields=['user'], name='plan_attend_user_id_f3733d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='planattendee',
            unique_together={('plan', 'user')},
        ),
    ]
