# Generated by Django 5.2.10 on 2026-02-01 15:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_plan_and_plan_attendee'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.plan')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_plan_messages', to='core.profile')),
            ],
            options={
                'db_table': 'plan_message',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['plan', 'created_at'], name='plan_messag_plan_id_3bc66c_idx')],
            },
        ),
    ]
