# Generated by Django 5.2.10 on 2026-02-02 23:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_person_match_unique_pair'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('activity_type', models.CharField(choices=[('climbing', 'Climbing'), ('snowboarding', 'Snowboarding'), ('skiing', 'Skiing'), ('hiking', 'Hiking'), ('kayaking', 'Kayaking'), ('surfing', 'Surfing'), ('biking', 'Biking'), ('camping', 'Camping'), ('coffee', 'Coffee'), ('cowork', 'Cowork'), ('potluck', 'Potluck'), ('campfire', 'Campfire'), ('dog_walk', 'Dog Walk'), ('sunset', 'Sunset'), ('sunrise_hike', 'Sunrise Hike'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('spots', models.PositiveIntegerField()),
                ('activity_date', models.DateField()),
                ('time_window', models.CharField(choices=[('morning', 'Morning (6am-12pm)'), ('afternoon', 'Afternoon (12pm-5pm)'), ('evening', 'Evening (5pm-9pm)'), ('flexible', 'Flexible')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('matched', 'Matched'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_activities', to='core.profile')),
            ],
            options={
                'db_table': 'activity',
                'ordering': ['activity_date', 'time_window'],
            },
        ),
        migrations.CreateModel(
            name='ActivityMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='core.activity')),
                ('attendees', models.ManyToManyField(related_name='activity_matches', to='core.profile')),
            ],
            options={
                'db_table': 'activity_match',
            },
        ),
        migrations.CreateModel(
            name='ActivityMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.activitymatch')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_activity_messages', to='core.profile')),
            ],
            options={
                'db_table': 'activity_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivitySwipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_like', models.BooleanField()),
                ('swiped_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to='core.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_swipes', to='core.profile')),
            ],
            options={
                'db_table': 'activity_swipe',
            },
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to='core.profile')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to='core.profile')),
            ],
            options={
                'db_table': 'friend_request',
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_as_user1', to='core.profile')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_as_user2', to='core.profile')),
            ],
            options={
                'db_table': 'friendship',
            },
        ),
        migrations.CreateModel(
            name='FriendMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_messages', to='core.profile')),
                ('friendship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.friendship')),
            ],
            options={
                'db_table': 'friend_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['status', 'activity_date'], name='activity_status_ab45c3_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['location'], name='activity_locatio_910f94_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['activity_type'], name='activity_activit_9541dd_idx'),
        ),
        migrations.AddIndex(
            model_name='activitymessage',
            index=models.Index(fields=['activity_match', 'created_at'], name='activity_me_activit_4e89f4_idx'),
        ),
        migrations.AddIndex(
            model_name='activityswipe',
            index=models.Index(fields=['activity', 'is_like'], name='activity_sw_activit_a4db7d_idx'),
        ),
        migrations.AddIndex(
            model_name='activityswipe',
            index=models.Index(fields=['user'], name='activity_sw_user_id_006028_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='activityswipe',
            unique_together={('activity', 'user')},
        ),
        migrations.AddIndex(
            model_name='friendrequest',
            index=models.Index(fields=['from_user', 'status'], name='friend_requ_from_us_24762d_idx'),
        ),
        migrations.AddIndex(
            model_name='friendrequest',
            index=models.Index(fields=['to_user', 'status'], name='friend_requ_to_user_d23c72_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('from_user', 'to_user')},
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['user1'], name='friendship_user1_i_e1895e_idx'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['user2'], name='friendship_user2_i_4de805_idx'),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(fields=('user1', 'user2'), name='unique_friendship'),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.CheckConstraint(condition=models.Q(('user1__lt', models.F('user2'))), name='user1_lt_user2'),
        ),
        migrations.AddIndex(
            model_name='friendmessage',
            index=models.Index(fields=['friendship', 'created_at'], name='friend_mess_friends_f11b97_idx'),
        ),
        migrations.AddIndex(
            model_name='friendmessage',
            index=models.Index(fields=['sender'], name='friend_mess_sender__f8229f_idx'),
        ),
    ]
