# Generated by Django 5.2.10 on 2026-02-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_activity_activitymatch_activitymessage_activityswipe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='interested_in_friends',
        ),
        migrations.AddField(
            model_name='profile',
            name='looking_for_friend_type',
            field=models.CharField(choices=[('any', 'Any'), ('singles_only', 'Singles Only'), ('couples_only', 'Couples Only'), ('no_preference', 'No Preference')], default='no_preference', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='relationship_status',
            field=models.CharField(choices=[('single', 'Single'), ('in_relationship', 'In a Relationship'), ('married', 'Married'), ('its_complicated', "It's Complicated"), ('prefer_not_to_say', 'Prefer Not to Say')], default='prefer_not_to_say', max_length=20),
        ),
    ]
