# Generated by Django 5.2.10 on 2026-02-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_profile_interested_in_friends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='next_month_in_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='next_week_in_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='now_in_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
