# Generated by Django 5.2.10 on 2026-02-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_city_location_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interested_in_men',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='interested_in_nonbinary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='interested_in_women',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profileprompt',
            name='prompt_question',
            field=models.CharField(choices=[('perfect_day', 'My perfect day on the road looks like...'), ('cant_live_without', "I can't live without..."), ('looking_for', "I'm looking for someone who..."), ('best_adventure', 'My best adventure so far...'), ('next_destination', 'My next dream destination is...'), ('van_life_lesson', 'The biggest lesson van life taught me...'), ('ideal_travel_buddy', 'My ideal travel buddy is...'), ('hidden_talent', 'My hidden talent is...'), ('campfire_story', 'A campfire story I love telling is...'), ('local_food', 'A local bite I never skip is...'), ('morning_ritual', 'My morning ritual on the road is...'), ('sunset_spot', 'The best sunset spot I have found is...'), ('road_trip_song', 'My road trip song on repeat is...'), ('spontaneous_plan', 'The most spontaneous thing I have done lately...'), ('travel_goal', 'One travel goal for this year is...'), ('outdoor_buddy', 'An outdoor activity I want a buddy for...'), ('city_or_smalltown', 'I prefer city or small town travel because...'), ('ideal_weekend', 'An ideal weekend with me looks like...'), ('coffee_order', 'My coffee order on the road is...'), ('hobby_to_share', 'A hobby I would love to share with someone...'), ('learn_from_you', "Something I'm curious to learn from you..."), ('open_invite', "If you're in town, let's..."), ('hidden_gem', 'A hidden gem I found recently is...'), ('travel_mascot', 'If I had a travel mascot, it would be...'), ('comfort_meal', 'My comfort meal on the road is...'), ('cat_travel_tip', 'My #1 tip for traveling with a cat is...'), ('cat_harness_routine', "My cat's harness or leash routine looks like..."), ('cat_personality', "My cat's road personality is..."), ('cat_safe_return', 'The trick that always brings my cat back to the van is...'), ('van_breakdown_story', 'The van breakdown that taught me the most was...'), ('van_build_feature', 'The best feature I built into my van is...'), ('move_frequency', 'I move campsites every ___ because...'), ('boondock_requirements', 'My ideal boondocking spot has...'), ('solo_safety_rule', 'My solo-travel safety rule is...'), ('trail_day_plan', 'My perfect trail day includes...'), ('sunrise_chase', 'A sunrise I would drive hours for is...'), ('offgrid_essentials', 'My off-grid essentials for a multi-day stretch are...'), ('park_and_work', 'My van work setup looks like...'), ('wildlife_moment', "A wildlife moment I'll never forget is..."), ('seasonal_route', 'A seasonal route I love to repeat is...')], max_length=50),
        ),
    ]
