# Generated by Django 5.2.10 on 2026-02-07 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_gender_preference_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='interested_in_dating',
        ),
    ]
