# Generated by Codex on 2026-02-07

from django.db import migrations, models


def mark_existing_profiles_completed(apps, schema_editor):
    Profile = apps.get_model('core', 'Profile')
    Profile.objects.exclude(display_name='').update(has_completed_onboarding=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_prompt_model_and_update_profile_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_completed_onboarding',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_existing_profiles_completed, migrations.RunPython.noop),
    ]
