# Generated by Codex on 2026-02-07

from django.db import migrations, models
import uuid


CITY_SEED_DATA = [
    'Moab, UT', 'Salt Lake City, UT', 'St. George, UT', 'Park City, UT', 'Kanab, UT',
    'Zion National Park, UT', 'Arches National Park, UT', 'Canyonlands, UT', 'Capitol Reef, UT',
    'Bryce Canyon, UT', 'Monument Valley, UT', 'Lake Powell, UT',
    'Denver, CO', 'Boulder, CO', 'Colorado Springs, CO', 'Fort Collins, CO', 'Durango, CO',
    'Telluride, CO', 'Aspen, CO', 'Steamboat Springs, CO', 'Estes Park, CO', 'Grand Junction, CO',
    'Ouray, CO', 'Crested Butte, CO', 'Glenwood Springs, CO',
    'Los Angeles, CA', 'San Diego, CA', 'San Francisco, CA', 'Joshua Tree, CA', 'Big Sur, CA',
    'Lake Tahoe, CA', 'Yosemite, CA', 'Death Valley, CA', 'Palm Springs, CA', 'Santa Barbara, CA',
    'Malibu, CA', 'Monterey, CA', 'Redwood National Park, CA', 'Sequoia National Park, CA',
    'Bishop, CA', 'Mammoth Lakes, CA', 'Ventura, CA', 'Santa Cruz, CA',
    'Las Vegas, NV', 'Reno, NV', 'Valley of Fire, NV', 'Lake Mead, NV', 'Great Basin, NV',
    'Phoenix, AZ', 'Tucson, AZ', 'Sedona, AZ', 'Flagstaff, AZ', 'Grand Canyon, AZ',
    'Page, AZ', 'Lake Havasu City, AZ', 'Prescott, AZ', 'Jerome, AZ', 'Bisbee, AZ',
    'Santa Fe, NM', 'Albuquerque, NM', 'Taos, NM', 'Carlsbad, NM', 'White Sands, NM',
    'Las Cruces, NM', 'Roswell, NM',
    'Austin, TX', 'San Antonio, TX', 'Big Bend, TX', 'Marfa, TX', 'El Paso, TX',
    'Fredericksburg, TX', 'South Padre Island, TX',
    'Portland, OR', 'Bend, OR', 'Eugene, OR', 'Ashland, OR', 'Crater Lake, OR',
    'Hood River, OR', 'Cannon Beach, OR', 'Astoria, OR',
    'Seattle, WA', 'Spokane, WA', 'Olympic National Park, WA', 'Mount Rainier, WA',
    'Bellingham, WA', 'Leavenworth, WA', 'Walla Walla, WA',
    'Bozeman, MT', 'Missoula, MT', 'Glacier National Park, MT', 'Whitefish, MT', 'Helena, MT',
    'Jackson Hole, WY', 'Yellowstone, WY', 'Grand Teton, WY', 'Cody, WY', 'Laramie, WY',
    'Boise, ID', 'Sun Valley, ID', "Coeur d'Alene, ID", 'McCall, ID',
    'Miami, FL', 'Key West, FL', 'Tampa, FL', 'Orlando, FL', 'St. Augustine, FL',
    'Everglades, FL', 'Destin, FL',
    'Nashville, TN', 'Asheville, NC', 'Charleston, SC', 'Savannah, GA',
    'New Orleans, LA', 'Acadia, ME', 'Burlington, VT', 'Bar Harbor, ME',
]


def seed_cities(apps, schema_editor):
    Country = apps.get_model('core', 'Country')
    City = apps.get_model('core', 'City')

    usa, _ = Country.objects.get_or_create(code='US', defaults={'name': 'United States'})

    for city in CITY_SEED_DATA:
        if ',' not in city:
            continue
        name, state_code = [part.strip() for part in city.split(',', 1)]
        if not name or not state_code:
            continue
        display_name = f"{name}, {state_code}"
        City.objects.get_or_create(
            name=name,
            state_code=state_code,
            country=usa,
            defaults={'display_name': display_name}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_profile_onboarding_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('state_code', models.CharField(max_length=2)),
                ('display_name', models.CharField(max_length=120, unique=True)),
                ('country', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='cities', to='core.country')),
            ],
            options={
                'db_table': 'city',
                'ordering': ['display_name'],
                'unique_together': {('name', 'state_code', 'country')},
            },
        ),
        migrations.RunPython(seed_cities, migrations.RunPython.noop),
    ]
