# Generated by Codex on 2026-02-07

from django.db import migrations, models


TRAVEL_PROMPTS = [
    ('next_stop_journey', 'Next stop on my journey:... – Update this with your upcoming destination or region (“the Rockies,” “Route 66,” “southern Utah”). It signals where you’ll be and invites nearby travelers to link up.'),
    ('always_down_team_up', 'Always down to team up for ____ when I’m on the road. – Whether it’s “sunrise hikes,” “scouting the best taco trucks in town,” or “impromptu photo shoots with our vans,” this shows what activities you want to share.'),
    ('looking_for_travel_buddy', 'Looking for a travel buddy to _____. – Finish with a bucket-list goal you’d love company for: “drive to the Arctic Circle,” “surf at sunrise,” or “explore hidden waterfalls.” It’s a direct call for a partner in crime.'),
    ('best_hidden_gem', 'The best hidden gem I’ve discovered on the road is... – Share a favorite secret spot (a campsite, quirky roadside cafe, hot spring, etc.). Not only does this show your travel style, it gives others a hook to say “I want to go there!”'),
    ('perfect_vanlife_meetup', 'My idea of a perfect vanlife meetup is... – Describe an ideal gathering: “a vans-and-coffee morning in a national park lot,” “a potluck dinner at a beach camp,” or “a convoy to the next music festival.” It sets a scene others might want to join.'),
    ('best_part_meeting_vanlifers', 'The best part about meeting other vanlifers is... – Reflect on why you love the community: “trading renovation tips,” “hearing wild travel stories,” or “instant understanding of this crazy lifestyle.” This highlights the camaraderie that makes others excited to meet up.'),
]

DATING_PROMPTS = [
    ('ideal_vanlife_date', 'My ideal vanlife date night is... – Paint a picture of a dreamy evening (think: stargazing by a campfire or cooking dinner by the canyon).'),
    ('well_get_along_if', 'We’ll get along if you enjoy... – Finish this with a vanlife pleasure: chasing sunsets, morning hikes from the van, or coffee brewed over a camp stove.'),
    ('impress_me_road_trip', 'If you want to impress me on a road trip, just... – Share a hook: maybe it’s curating the perfect driving playlist, brewing pour-over coffee at sunrise, or knowing a secret free campsite.'),
    ('quickest_way_to_heart', 'The quickest way to my heart on the road is... – Whether it’s “making s’mores under the Milky Way” or “being calm during a tire change,” show what wins you over.'),
    ('dating_me_means', 'Dating me means accepting... – Complete with a quirky truth about your lifestyle: “that my cat rides shotgun,” “campground Wi-Fi dates,” or “I own more hiking boots than fancy shoes.”'),
    ('swipe_right_if', 'I’ll definitely swipe right if you also love... – Mention a passion you’d love a partner to share: national parks, skinny-dipping in hot springs, epic road playlists, etc.'),
    ('most_romantic_spot', 'The most romantic spot I’ve camped at is... – Tease your favorite magical location (e.g. “a hidden beach cove in Big Sur”) to intrigue adventure-loving matches.'),
]

FRIENDSHIP_PROMPTS = [
    ('friend_need', 'If you need a friend to ____, I’m your person. – Fill in with something like “watch your van while you take a supply run” or “start a campfire and jam on a guitar.” It signals reliability and fun.'),
    ('go_to_campfire_story', 'My go-to campfire story is about the time... – Hint at an epic or funny vanlife adventure (maybe “that time I got my van unstuck from mud with a herd of cows watching”). It’s an instant conversation starter.'),
    ('best_vanlife_hack', 'The best vanlife hack I’ve learned is... – Share a handy tip (e.g. “using fairy lights as a cozy nightlight” or “stashing a secret chocolate supply”). Practical or quirky, it shows your road wisdom.'),
    ('friends_know_me_as', 'My friends know me as the ____ one on road trips. – Are you “the early-riser sunrise chaser,” “the mechanic who can fix anything,” or “the laid-back hammock napper”? Highlight your road-trip role.'),
    ('instant_friends_if', 'We’ll instantly be friends if you _____. – Finish with something fellow vanlifers relate to: “wave at other van dwellers on the highway,” “can name at least 5 constellations,” or “don’t mind a little sand in your bed.”'),
    ('motto_i_travel_by', 'The motto I travel by is... – Share a short credo that guides you (e.g. “Adventure before comfort,” “Leave no trace,” or “Home is where I park it”). It gives insight into your vibe and values.'),
    ('traveling_with_my_pet', 'Traveling with my pet taught me... – Many vanlifers have adventure pets, like Quin’s cat Atlas. Use this prompt to share a lesson or funny insight (e.g. “...taught me that every window is a TV for my cat” or “...that dogs can be co-pilots and crumb catchers at once”).'),
]


def reseed_prompts(apps, schema_editor):
    Prompt = apps.get_model('core', 'Prompt')
    ProfilePrompt = apps.get_model('core', 'ProfilePrompt')

    ProfilePrompt.objects.all().delete()
    Prompt.objects.all().delete()

    for name, question in TRAVEL_PROMPTS:
        Prompt.objects.create(prompt_name=name, prompt_question=question, prompt_type='travel')
    for name, question in DATING_PROMPTS:
        Prompt.objects.create(prompt_name=name, prompt_question=question, prompt_type='dating')
    for name, question in FRIENDSHIP_PROMPTS:
        Prompt.objects.create(prompt_name=name, prompt_question=question, prompt_type='friendship')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_city_model_and_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='prompt_type',
            field=models.CharField(choices=[('travel', 'Travel'), ('dating', 'Dating'), ('friendship', 'Friendship')], default='travel', max_length=20),
            preserve_default=False,
        ),
        migrations.RunPython(reseed_prompts, migrations.RunPython.noop),
    ]
