# Generated by Codex on 2026-02-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_add_prompt_placeholder_and_reseed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('man', 'Man'), ('woman', 'Woman'), ('non_binary', 'Non-binary')], max_length=20, null=True),
        ),
    ]
