# Generated by Django 5.2.10 on 2026-02-08 17:05
# Manually cleaned to remove stale operations for already-deleted models

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_region_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('coffee', 'Coffee'), ('potluck', 'Potluck'), ('campfire', 'Campfire'), ('cowork', 'Cowork Session'), ('hiking', 'Hiking'), ('sunrise_hike', 'Sunrise Hike'), ('sunset', 'Sunset Viewpoint'), ('climbing', 'Climbing'), ('biking', 'Biking'), ('kayaking', 'Kayaking'), ('surfing', 'Surfing'), ('camping', 'Camping'), ('snowboarding', 'Snowboarding'), ('skiing', 'Skiing'), ('dog_walk', 'Dog Walk'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('join_mode', models.CharField(choices=[('direct', 'Direct Join'), ('swipe', 'Swipe to Join')], max_length=20)),
                ('spots', models.PositiveIntegerField()),
                ('event_date', models.DateField()),
                ('time_window', models.CharField(choices=[('morning', 'Morning (6am-12pm)'), ('afternoon', 'Afternoon (12pm-5pm)'), ('evening', 'Evening (5pm-9pm)'), ('flexible', 'Flexible')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('full', 'Full'), ('matched', 'Matched'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event',
                'ordering': ['event_date', 'time_window'],
            },
        ),
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('joined', 'Joined'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='joined', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'event_attendee',
            },
        ),
        migrations.CreateModel(
            name='EventMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventSwipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_like', models.BooleanField()),
                ('swiped_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_swipe',
            },
        ),
        # Add indexes to City model
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['display_name'], name='city_display_57c3f8_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name'], name='city_name_88111b_idx'),
        ),
        # Add foreign keys to Event
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to='core.profile'),
        ),
        # Add foreign keys to EventAttendee
        migrations.AddField(
            model_name='eventattendee',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='core.event'),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to='core.profile'),
        ),
        # Add foreign keys to EventMessage
        migrations.AddField(
            model_name='eventmessage',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.event'),
        ),
        migrations.AddField(
            model_name='eventmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_event_messages', to='core.profile'),
        ),
        # Add foreign keys to EventSwipe
        migrations.AddField(
            model_name='eventswipe',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to='core.event'),
        ),
        migrations.AddField(
            model_name='eventswipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_swipes', to='core.profile'),
        ),
        # Add indexes to Event
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'event_date'], name='event_status_09239b_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['join_mode', 'status'], name='event_join_mo_7134fc_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['location'], name='event_locatio_6e679d_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type'], name='event_event_t_4c9c3b_idx'),
        ),
        # Add unique constraints
        migrations.AlterUniqueTogether(
            name='eventattendee',
            unique_together={('event', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='eventswipe',
            unique_together={('event', 'user')},
        ),
    ]
