# Generated by Django 5.2.10 on 2026-02-08 17:06

from django.db import migrations


def migrate_plans_to_events(apps, schema_editor):
    """
    Migrate existing Plan records to Event with join_mode='direct'.
    
    Field mapping:
    - plan.plan_type → event.event_type
    - plan.plan_date → event.event_date
    - plan.meetup_area → event.location
    - plan.max_attendees → event.spots
    - Set join_mode='direct'
    """
    Plan = apps.get_model('core', 'Plan')
    Event = apps.get_model('core', 'Event')
    
    for plan in Plan.objects.all():
        Event.objects.create(
            id=plan.id,  # Preserve IDs for easier debugging
            created_by=plan.created_by,
            title=plan.title,
            event_type=plan.plan_type,
            description=plan.description,
            image_url=None,  # Plans don't have image_url
            join_mode='direct',
            spots=plan.max_attendees,
            event_date=plan.plan_date,
            time_window=plan.time_window,
            location=plan.meetup_area,
            status=plan.status,
            created_at=plan.created_at,
        )


def reverse_migrate_plans_to_events(apps, schema_editor):
    """
    Reverse migration: Delete Event records that were migrated from Plans.
    
    We identify these by join_mode='direct' since all Plan migrations
    use this mode.
    """
    Event = apps.get_model('core', 'Event')
    
    # Delete events with join_mode='direct' (migrated from Plans)
    Event.objects.filter(join_mode='direct').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_event_eventattendee_eventmessage_eventswipe_and_more'),
    ]

    operations = [
        migrations.RunPython(
            migrate_plans_to_events,
            reverse_migrate_plans_to_events,
        ),
    ]
