# Generated by Django 5.2.10 on 2026-02-08 17:10

from django.db import migrations


def migrate_activities_to_events(apps, schema_editor):
    """
    Migrate existing Activity records to Event with join_mode='swipe'.
    
    Field mapping:
    - activity.activity_type → event.event_type
    - activity.activity_date → event.event_date
    - activity.location → event.location
    - activity.spots → event.spots
    - activity.image_url → event.image_url
    - Set join_mode='swipe'
    
    Validates: Requirements 6.2
    """
    Activity = apps.get_model('core', 'Activity')
    Event = apps.get_model('core', 'Event')
    
    for activity in Activity.objects.all():
        Event.objects.create(
            id=activity.id,  # Preserve IDs for easier debugging
            created_by=activity.created_by,
            title=activity.title,
            event_type=activity.activity_type,
            description=activity.description,
            image_url=activity.image_url,
            join_mode='swipe',
            spots=activity.spots,
            event_date=activity.activity_date,
            time_window=activity.time_window,
            location=activity.location,
            status=activity.status,
            created_at=activity.created_at,
        )


def reverse_migrate_activities_to_events(apps, schema_editor):
    """
    Reverse migration: Delete Event records that were migrated from Activities.
    
    We identify these by join_mode='swipe' since all Activity migrations
    use this mode.
    """
    Event = apps.get_model('core', 'Event')
    
    # Delete events with join_mode='swipe' (migrated from Activities)
    Event.objects.filter(join_mode='swipe').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_migrate_plans_to_events'),
    ]

    operations = [
        migrations.RunPython(
            migrate_activities_to_events,
            reverse_migrate_activities_to_events,
        ),
    ]
