# Generated by Django 5.2.10 on 2026-02-08 17:12

from django.db import migrations


def migrate_plan_attendees_to_event_attendees(apps, schema_editor):
    """
    Migrate existing PlanAttendee records to EventAttendee.
    
    Field mapping:
    - plan_attendee.plan → event_attendee.event (via plan.id which matches event.id)
    - plan_attendee.user → event_attendee.user
    - plan_attendee.status → event_attendee.status
    - plan_attendee.joined_at → event_attendee.joined_at
    - plan_attendee.confirmed_at → event_attendee.confirmed_at
    
    Note: The Event ID matches the original Plan ID (from migration 0038),
    so we use plan.id to find the corresponding Event.
    """
    PlanAttendee = apps.get_model('core', 'PlanAttendee')
    Event = apps.get_model('core', 'Event')
    EventAttendee = apps.get_model('core', 'EventAttendee')
    
    for plan_attendee in PlanAttendee.objects.all():
        # Find the corresponding Event (has same ID as the Plan)
        try:
            event = Event.objects.get(id=plan_attendee.plan.id)
        except Event.DoesNotExist:
            # Skip if the corresponding Event doesn't exist
            continue
        
        # Create EventAttendee with the same data
        EventAttendee.objects.create(
            event=event,
            user=plan_attendee.user,
            status=plan_attendee.status,
            joined_at=plan_attendee.joined_at,
            confirmed_at=plan_attendee.confirmed_at,
        )


def reverse_migrate_plan_attendees(apps, schema_editor):
    """
    Reverse migration: Delete EventAttendee records that were migrated from PlanAttendees.
    
    We identify these by finding EventAttendees linked to Events with join_mode='direct'
    since all Plan migrations use this mode.
    """
    Event = apps.get_model('core', 'Event')
    EventAttendee = apps.get_model('core', 'EventAttendee')
    
    # Get all events that were migrated from Plans (join_mode='direct')
    direct_event_ids = Event.objects.filter(join_mode='direct').values_list('id', flat=True)
    
    # Delete EventAttendees linked to these events
    EventAttendee.objects.filter(event_id__in=list(direct_event_ids)).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_migrate_activities_to_events'),
    ]

    operations = [
        migrations.RunPython(
            migrate_plan_attendees_to_event_attendees,
            reverse_migrate_plan_attendees,
        ),
    ]
