# Generated by Django 5.2.10 on 2026-02-08 17:14

from django.db import migrations


def migrate_activity_swipes_to_event_swipes(apps, schema_editor):
    """
    Migrate existing ActivitySwipe records to EventSwipe.
    
    Field mapping:
    - activity_swipe.activity → event_swipe.event (via activity.id which matches event.id)
    - activity_swipe.user → event_swipe.user
    - activity_swipe.is_like → event_swipe.is_like
    - activity_swipe.swiped_at → event_swipe.swiped_at
    
    Note: The Event ID matches the original Activity ID (from migration 0039),
    so we use activity.id to find the corresponding Event.
    
    We use bulk_create with update_fields to preserve the original swiped_at timestamps.
    Since swiped_at has auto_now_add=True, we need to update it after creation.
    
    Validates: Requirements 6.4
    """
    ActivitySwipe = apps.get_model('core', 'ActivitySwipe')
    Event = apps.get_model('core', 'Event')
    EventSwipe = apps.get_model('core', 'EventSwipe')
    
    # Build a mapping of activity_id -> event for quick lookup
    swipe_events = {e.id: e for e in Event.objects.filter(join_mode='swipe')}
    
    for activity_swipe in ActivitySwipe.objects.all():
        # Find the corresponding Event (has same ID as the Activity)
        event = swipe_events.get(activity_swipe.activity_id)
        if not event:
            # Skip if the corresponding Event doesn't exist
            continue
        
        # Create EventSwipe - auto_now_add will set swiped_at to now
        event_swipe = EventSwipe.objects.create(
            event=event,
            user=activity_swipe.user,
            is_like=activity_swipe.is_like,
        )
        
        # Update swiped_at to preserve the original timestamp
        # Using update() bypasses auto_now_add
        EventSwipe.objects.filter(pk=event_swipe.pk).update(
            swiped_at=activity_swipe.swiped_at
        )


def reverse_migrate_activity_swipes(apps, schema_editor):
    """
    Reverse migration: Delete EventSwipe records that were migrated from ActivitySwipes.
    
    We identify these by finding EventSwipes linked to Events with join_mode='swipe'
    since all Activity migrations use this mode.
    """
    Event = apps.get_model('core', 'Event')
    EventSwipe = apps.get_model('core', 'EventSwipe')
    
    # Get all events that were migrated from Activities (join_mode='swipe')
    swipe_event_ids = Event.objects.filter(join_mode='swipe').values_list('id', flat=True)
    
    # Delete EventSwipes linked to these events
    EventSwipe.objects.filter(event_id__in=list(swipe_event_ids)).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_migrate_plan_attendees'),
    ]

    operations = [
        migrations.RunPython(
            migrate_activity_swipes_to_event_swipes,
            reverse_migrate_activity_swipes,
        ),
    ]
