# Generated by Django 5.2.10 on 2026-02-08 17:16

from django.db import migrations


def migrate_activity_match_attendees_to_event_attendees(apps, schema_editor):
    """
    Migrate existing ActivityMatch attendees to EventAttendee.
    
    Field mapping:
    - activity_match.activity → event (via activity.id which matches event.id)
    - activity_match.attendees (ManyToMany) → EventAttendee records
    - activity_match.matched_at → event_attendee.joined_at
    - status is set to 'confirmed' since these are matched attendees
    
    Note: The Event ID matches the original Activity ID (from migration 0039),
    so we use activity.id to find the corresponding Event.
    
    Since joined_at has auto_now_add=True, we need to update it after creation
    to preserve the original matched_at timestamp.
    
    Validates: Requirements 6.5
    """
    ActivityMatch = apps.get_model('core', 'ActivityMatch')
    Event = apps.get_model('core', 'Event')
    EventAttendee = apps.get_model('core', 'EventAttendee')
    
    # Build a mapping of activity_id -> event for quick lookup
    swipe_events = {e.id: e for e in Event.objects.filter(join_mode='swipe')}
    
    for activity_match in ActivityMatch.objects.all():
        # Find the corresponding Event (has same ID as the Activity)
        event = swipe_events.get(activity_match.activity_id)
        if not event:
            # Skip if the corresponding Event doesn't exist
            continue
        
        # Migrate each attendee from the ManyToMany relationship
        for attendee in activity_match.attendees.all():
            # Create EventAttendee - auto_now_add will set joined_at to now
            event_attendee = EventAttendee.objects.create(
                event=event,
                user=attendee,
                status='confirmed',
            )
            
            # Update joined_at to preserve the original matched_at timestamp
            # Using update() bypasses auto_now_add
            EventAttendee.objects.filter(pk=event_attendee.pk).update(
                joined_at=activity_match.matched_at
            )


def reverse_migrate_activity_match_attendees(apps, schema_editor):
    """
    Reverse migration: Delete EventAttendee records that were migrated from ActivityMatch.
    
    We identify these by finding EventAttendees linked to Events with join_mode='swipe'
    and status='confirmed' since all ActivityMatch attendees are migrated with this status.
    """
    Event = apps.get_model('core', 'Event')
    EventAttendee = apps.get_model('core', 'EventAttendee')
    
    # Get all events that were migrated from Activities (join_mode='swipe')
    swipe_event_ids = Event.objects.filter(join_mode='swipe').values_list('id', flat=True)
    
    # Delete EventAttendees linked to these events with 'confirmed' status
    # (ActivityMatch attendees are migrated with status='confirmed')
    EventAttendee.objects.filter(
        event_id__in=list(swipe_event_ids),
        status='confirmed'
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_migrate_activity_swipes'),
    ]

    operations = [
        migrations.RunPython(
            migrate_activity_match_attendees_to_event_attendees,
            reverse_migrate_activity_match_attendees,
        ),
    ]
