# Generated by Django 5.2.10 on 2026-02-08 17:19

from django.db import migrations


def migrate_plan_messages_to_event_messages(apps, schema_editor):
    """
    Migrate existing PlanMessage records to EventMessage.
    
    Field mapping:
    - plan_message.plan → event (via plan.id which matches event.id)
    - plan_message.sender → event_message.sender
    - plan_message.content → event_message.content
    - plan_message.created_at → event_message.created_at
    
    Note: The Event ID matches the original Plan ID (from migration 0038),
    so we use plan.id to find the corresponding Event.
    
    Since created_at has auto_now_add=True, we need to update it after creation
    to preserve the original timestamp.
    """
    PlanMessage = apps.get_model('core', 'PlanMessage')
    Event = apps.get_model('core', 'Event')
    EventMessage = apps.get_model('core', 'EventMessage')
    
    # Build a mapping of plan_id -> event for quick lookup
    # Events migrated from Plans have join_mode='direct'
    direct_events = {e.id: e for e in Event.objects.filter(join_mode='direct')}
    
    for plan_message in PlanMessage.objects.all():
        # Find the corresponding Event (has same ID as the Plan)
        event = direct_events.get(plan_message.plan_id)
        if not event:
            # Skip if the corresponding Event doesn't exist
            continue
        
        # Create EventMessage - auto_now_add will set created_at to now
        event_message = EventMessage.objects.create(
            event=event,
            sender=plan_message.sender,
            content=plan_message.content,
        )
        
        # Update created_at to preserve the original timestamp
        # Using update() bypasses auto_now_add
        EventMessage.objects.filter(pk=event_message.pk).update(
            created_at=plan_message.created_at
        )


def reverse_migrate_plan_messages(apps, schema_editor):
    """
    Reverse migration: Delete EventMessage records that were migrated from PlanMessage.
    
    We identify these by finding EventMessages linked to Events with join_mode='direct'
    since all PlanMessages are migrated to Events with this join_mode.
    """
    Event = apps.get_model('core', 'Event')
    EventMessage = apps.get_model('core', 'EventMessage')
    
    # Get all events that were migrated from Plans (join_mode='direct')
    direct_event_ids = Event.objects.filter(join_mode='direct').values_list('id', flat=True)
    
    # Delete EventMessages linked to these events
    EventMessage.objects.filter(event_id__in=list(direct_event_ids)).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_migrate_activity_match_attendees'),
    ]

    operations = [
        migrations.RunPython(
            migrate_plan_messages_to_event_messages,
            reverse_migrate_plan_messages,
        ),
    ]
