# Generated by Django 5.2.10 on 2026-02-08 17:21

from django.db import migrations


def migrate_activity_messages_to_event_messages(apps, schema_editor):
    """
    Migrate existing ActivityMessage records to EventMessage.
    
    Field mapping:
    - activity_message.activity_match.activity → event (via activity.id which matches event.id)
    - activity_message.sender → event_message.sender
    - activity_message.content → event_message.content
    - activity_message.created_at → event_message.created_at
    
    Note: ActivityMessage is linked to ActivityMatch, which has a OneToOne to Activity.
    The Event ID matches the original Activity ID (from migration 0039),
    so we use activity_match.activity.id to find the corresponding Event.
    
    Since created_at has auto_now_add=True, we need to update it after creation
    to preserve the original timestamp.
    """
    ActivityMessage = apps.get_model('core', 'ActivityMessage')
    Event = apps.get_model('core', 'Event')
    EventMessage = apps.get_model('core', 'EventMessage')
    
    # Build a mapping of activity_id -> event for quick lookup
    # Events migrated from Activities have join_mode='swipe'
    swipe_events = {e.id: e for e in Event.objects.filter(join_mode='swipe')}
    
    for activity_message in ActivityMessage.objects.select_related('activity_match__activity').all():
        # Get the Activity ID via the ActivityMatch
        activity_id = activity_message.activity_match.activity_id
        
        # Find the corresponding Event (has same ID as the Activity)
        event = swipe_events.get(activity_id)
        if not event:
            # Skip if the corresponding Event doesn't exist
            continue
        
        # Create EventMessage - auto_now_add will set created_at to now
        event_message = EventMessage.objects.create(
            event=event,
            sender=activity_message.sender,
            content=activity_message.content,
        )
        
        # Update created_at to preserve the original timestamp
        # Using update() bypasses auto_now_add
        EventMessage.objects.filter(pk=event_message.pk).update(
            created_at=activity_message.created_at
        )


def reverse_migrate_activity_messages(apps, schema_editor):
    """
    Reverse migration: Delete EventMessage records that were migrated from ActivityMessage.
    
    We identify these by finding EventMessages linked to Events with join_mode='swipe'
    since all ActivityMessages are migrated to Events with this join_mode.
    """
    Event = apps.get_model('core', 'Event')
    EventMessage = apps.get_model('core', 'EventMessage')
    
    # Get all events that were migrated from Activities (join_mode='swipe')
    swipe_event_ids = Event.objects.filter(join_mode='swipe').values_list('id', flat=True)
    
    # Delete EventMessages linked to these events
    EventMessage.objects.filter(event_id__in=list(swipe_event_ids)).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_migrate_plan_messages'),
    ]

    operations = [
        migrations.RunPython(
            migrate_activity_messages_to_event_messages,
            reverse_migrate_activity_messages,
        ),
    ]
