# Generated by Django 5.2.10 on 2026-02-09 14:48
# Modified to handle legacy tables already dropped by migration 0045

import django.db.models.deletion
import uuid
from django.db import migrations, models


def safe_drop_legacy_tables_and_indexes(apps, schema_editor):
    """
    Safely drop legacy tables and indexes that may or may not exist.
    Migration 0045 already dropped some of these via raw SQL, but Django's
    migration state still references them. This cleans up any remnants.
    """
    # Drop indexes that may have been removed when their columns were dropped
    indexes_to_remove = [
        'profile_now_in__ad2c8e_idx',
        'profile_next_we_793543_idx',
        'profile_next_mo_a09eeb_idx',
    ]

    legacy_tables = [
        'activity_message',
        'activity_match_attendees',
        'activity_match',
        'activity_swipe',
        'activity',
        'answer_option',
        'candidate_term',
        'candidate',
        'group_membership',
        'session_shared_group',
        'session',
        '"group"',  # quoted because 'group' is a reserved word
        'match_message',
        'match',
        'plan_message',
        'plan_attendee',
        'plan',
        'question',
        'swipe',
        'taxonomy',
        'term',
        'user_answer',
    ]

    with schema_editor.connection.cursor() as cursor:
        for idx in indexes_to_remove:
            cursor.execute(f"DROP INDEX IF EXISTS {idx};")
        for table in legacy_tables:
            cursor.execute(f"DROP TABLE IF EXISTS {table} CASCADE;")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_friend_message_model'),
    ]

    operations = [
        # 1. Create the new ProfilePhoto model
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_type', models.CharField(choices=[('avatar', 'Avatar'), ('cover', 'Cover'), ('gallery', 'Gallery')], max_length=10)),
                ('image', models.ImageField(upload_to='profile_photos/%Y/%m/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'profile_photo',
                'ordering': ['display_order', '-created_at'],
            },
        ),

        # 2. Safely drop legacy tables and indexes at the DB level
        migrations.RunPython(
            safe_drop_legacy_tables_and_indexes,
            migrations.RunPython.noop,
        ),

        # 3. Add profile FK to ProfilePhoto
        migrations.AddField(
            model_name='profilephoto',
            name='profile',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='photos',
                to='core.profile',
            ),
        ),

        # 4. Remove legacy models from Django's migration state only.
        #    The actual tables were already dropped above (or by migration 0045).
        #    SeparateDatabaseAndState lets us update Django's state without
        #    touching the database.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(model_name='activity', name='created_by'),
                migrations.RemoveField(model_name='activityswipe', name='activity'),
                migrations.RemoveField(model_name='activitymatch', name='activity'),
                migrations.RemoveField(model_name='activitymatch', name='attendees'),
                migrations.RemoveField(model_name='activitymessage', name='activity_match'),
                migrations.RemoveField(model_name='activitymessage', name='sender'),
                migrations.AlterUniqueTogether(name='activityswipe', unique_together=None),
                migrations.RemoveField(model_name='activityswipe', name='user'),
                migrations.RemoveField(model_name='answeroption', name='question'),
                migrations.RemoveField(model_name='useranswer', name='answer_option'),
                migrations.AlterUniqueTogether(name='candidate', unique_together=None),
                migrations.RemoveField(model_name='candidate', name='created_by'),
                migrations.RemoveField(model_name='candidate', name='session'),
                migrations.RemoveField(model_name='candidateterm', name='candidate'),
                migrations.RemoveField(model_name='swipe', name='candidate'),
                migrations.RemoveField(model_name='match', name='candidate'),
                migrations.AlterUniqueTogether(name='candidateterm', unique_together=None),
                migrations.RemoveField(model_name='candidateterm', name='term'),
                migrations.RemoveField(model_name='group', name='created_by'),
                migrations.RemoveField(model_name='groupmembership', name='group'),
                migrations.RemoveField(model_name='session', name='group'),
                migrations.RemoveField(model_name='sessionsharedgroup', name='group'),
                migrations.AlterUniqueTogether(name='groupmembership', unique_together=None),
                migrations.RemoveField(model_name='groupmembership', name='user'),
                migrations.AlterUniqueTogether(name='match', unique_together=None),
                migrations.RemoveField(model_name='match', name='session'),
                migrations.RemoveField(model_name='matchmessage', name='match'),
                migrations.RemoveField(model_name='matchmessage', name='user'),
                migrations.RemoveField(model_name='plan', name='created_by'),
                migrations.RemoveField(model_name='planmessage', name='plan'),
                migrations.RemoveField(model_name='planattendee', name='plan'),
                migrations.AlterUniqueTogether(name='planattendee', unique_together=None),
                migrations.RemoveField(model_name='planattendee', name='user'),
                migrations.RemoveField(model_name='planmessage', name='sender'),
                migrations.RemoveField(model_name='useranswer', name='question'),
                migrations.RemoveField(model_name='useranswer', name='session'),
                migrations.RemoveField(model_name='sessionsharedgroup', name='session'),
                migrations.AlterUniqueTogether(name='sessionsharedgroup', unique_together=None),
                migrations.AlterUniqueTogether(name='swipe', unique_together=None),
                migrations.RemoveField(model_name='swipe', name='user'),
                migrations.RemoveField(model_name='term', name='taxonomy'),
                migrations.AlterUniqueTogether(name='term', unique_together=None),
                migrations.AlterUniqueTogether(name='useranswer', unique_together=None),
                migrations.RemoveField(model_name='useranswer', name='user'),
                migrations.RemoveIndex(model_name='profile', name='profile_now_in__ad2c8e_idx'),
                migrations.RemoveIndex(model_name='profile', name='profile_next_we_793543_idx'),
                migrations.RemoveIndex(model_name='profile', name='profile_next_mo_a09eeb_idx'),
                migrations.DeleteModel(name='Activity'),
                migrations.DeleteModel(name='ActivityMatch'),
                migrations.DeleteModel(name='ActivityMessage'),
                migrations.DeleteModel(name='ActivitySwipe'),
                migrations.DeleteModel(name='AnswerOption'),
                migrations.DeleteModel(name='Candidate'),
                migrations.DeleteModel(name='CandidateTerm'),
                migrations.DeleteModel(name='Group'),
                migrations.DeleteModel(name='GroupMembership'),
                migrations.DeleteModel(name='Match'),
                migrations.DeleteModel(name='MatchMessage'),
                migrations.DeleteModel(name='Plan'),
                migrations.DeleteModel(name='PlanAttendee'),
                migrations.DeleteModel(name='PlanMessage'),
                migrations.DeleteModel(name='Question'),
                migrations.DeleteModel(name='Session'),
                migrations.DeleteModel(name='SessionSharedGroup'),
                migrations.DeleteModel(name='Swipe'),
                migrations.DeleteModel(name='Taxonomy'),
                migrations.DeleteModel(name='Term'),
                migrations.DeleteModel(name='UserAnswer'),
            ],
            database_operations=[],
        ),

        # 5. Add index on ProfilePhoto
        migrations.AddIndex(
            model_name='profilephoto',
            index=models.Index(
                fields=['profile', 'photo_type'],
                name='profile_pho_profile_89497b_idx',
            ),
        ),
    ]
