# Generated by Django 5.2.10 on 2026-02-12 22:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_usersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuilderListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('category', models.CharField(choices=[('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('carpentry', 'Carpentry'), ('mechanical', 'Mechanical'), ('painting', 'Painting'), ('insulation', 'Insulation'), ('solar', 'Solar'), ('general', 'General')], max_length=20)),
                ('listing_type', models.CharField(choices=[('offering', 'Offering'), ('requesting', 'Requesting')], max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('photo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builder_listings', to='core.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builder_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'builder_listing',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='builder_lis_categor_e5e9f4_idx'), models.Index(fields=['listing_type'], name='builder_lis_listing_5a5025_idx'), models.Index(fields=['is_active', '-created_at'], name='builder_lis_is_acti_4fab05_idx')],
            },
        ),
    ]
