# Generated by Django 5.2.10 on 2026-02-12 22:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_builderlisting'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuilderMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=1000)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.builderlisting')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_builder_messages', to='core.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_builder_messages', to='core.profile')),
            ],
            options={
                'db_table': 'builder_message',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['listing', 'sender', 'recipient'], name='builder_mes_listing_8ad20d_idx'), models.Index(fields=['listing', 'created_at'], name='builder_mes_listing_44d741_idx')],
            },
        ),
    ]
