# Generated by Django 5.2.10 on 2026-02-13 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_city_geo_fields_and_platform_events'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='follow',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='following',
        ),
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='to_user',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='user2',
        ),
        migrations.RemoveField(
            model_name='directmessage',
            name='friendship',
        ),
        # Remove constraint if it exists (may not exist in fresh DBs due to migration squashing)
        migrations.RunSQL(
            "ALTER TABLE direct_message DROP CONSTRAINT IF EXISTS direct_message_has_one_parent;",
            migrations.RunSQL.noop,
        ),
        # Remove friendship index if it exists
        migrations.RunSQL(
            "DROP INDEX IF EXISTS direct_mess_friends_443e60_idx;",
            migrations.RunSQL.noop,
        ),
        # Delete any orphaned messages that had friendship but no match
        migrations.RunSQL(
            "DELETE FROM direct_message WHERE match_id IS NULL;",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.personmatch'),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
